---
title: "HW_02"
author: "Chantsal 108035487"
date: "4/4/2020"
output:
  html_document: default
  pdf_document: default
---

## Q1. Find the tangency portfolio with no short-sale constraint.
     Risk-free rate is assumed to be 1% per annum.

```{r}
library(quantmod)
library(plyr)
library(xts)
library(quadprog)
library(fBasics)
library(stats)
tickers <- c("COST", "WMT", "TGT")
getSymbols(tickers, from= "2007-01-01", to= "2009-12-31")
data.env<-new.env()
l_ply(tickers, function(sym) try(getSymbols(sym, env=data.env), silent=T))
stocks <- tickers[tickers %in% ls(data.env)]
data <- xts()

for(i in seq_along(stocks)) {
  symbol <- stocks[i]
  data <- merge(data, Ad(get(symbol, envir=data.env)))
}


mu = apply(data, 2, mean)
Sigma = cov(data)
std = sqrt(diag(Sigma))
Amat1 = cbind(rep(1,3),mu, diag(1,nrow=3))  
t(Amat1)
# muP = seq(.01,.08,length=300)  # set of 300 possible target values 
# When short sales are prohibited, the target expected return on the 
# portfolio must lie between the smallest 
# and largest expected returns on the stocks. 
muP = seq(min(mu)+.0001,max(mu)-.0001,length=300)
sdP = muP # set up storage for standard deviations of portfolio returns
weights = matrix(0,nrow=300,ncol=3) # storage for portfolio weights

i=1
for (i in 1:length(muP))  # find the optimal portfolios for each target expected return
{
  bvec1 = c(1,muP[i], rep(0,3))  # constraint vector
  result = solve.QP(Dmat=2*Sigma,dvec=rep(0,3),Amat=Amat1,bvec=bvec1,meq=2)
  sdP[i] = sqrt(result$value)
  weights[i,] = result$solution
}


plot(sdP,muP,type="l",xlim=c(0,0.25),ylim=c(0,0.08),lty=1)
par(new=TRUE)
plot(sdP,muP,type="l",xlim=c(0,0.25),ylim=c(0,0.08),lty=1, col="green")
mufree = 0.01/12 # input value of risk-free interest rate
points(0,mufree,cex=3, pch="*")  # show risk-free asset
sharpe =( muP-mufree)/sdP # compute Sharpe ratios
ind = (sharpe == max(sharpe)) # Find maximum Sharpe ratio
options(digits=3)
weights[ind,] # Find tangency portfolio# show line of optimal portfolios
lines(c(0,2),mufree+c(0,2)*(muP[ind]-mufree)/sdP[ind],lwd=2,lty=3)
# show line of optimal portfolios
points(sdP[ind],muP[ind],cex=1,pch=19, col="red") # show tangency portfolio
ind2 = (sdP == min(sdP)) # find the minimum variance portfolio
points(sdP[ind2],muP[ind2],cex=2,pch="+", col="blue") # show minimum variance portfolio
ind3 = (muP > muP[ind2])
lines(sdP[ind3],muP[ind3],type="l",xlim=c(0,.25),
      ylim=c(0,.08),lwd=1)  #  plot the efficient frontier
points(c(std[1],std[2], std[3]), c(mu[1], mu[2], mu[3]), cex=1, pch="o", col="red") 
text(std[1],mu[1],"Costco",cex=1, pos=4)
text(std[2],mu[2],"Wallmart",cex=1, pos=4)
text(std[3],mu[3],"Target",cex=1, pos=4)
graphics.off()

```


## Q2.Plot the efficient frontier with and without short-sale constraint.
```{r}
con = gzcon(url('https://github.com/systematicinvestor/SIT/raw/master/sit.gz', 'rb'))
source(con)
close(con)

tickers <- c("COST", "WMT", "TGT")
n <- length(tickers)
#with short sale constraint.
constraints = new.constraints(n, lb = -Inf, ub = +Inf)

constraints = add.constraints(rep(1, n), 1, type = '=', constraints)        
ia<- create.historical.ia(ret, 250)

weight <- min.risk.portfolio(ia, constraints)
#without short sale constraint.
ia<- create.historical.ia(ret, 250)
constraints = new.constraints(n, lb = 0, ub = 1)
constraints = add.constraints(diag(n), type='>=', b=0, constraints)
constraints = add.constraints(diag(n), type='<=', b=1, constraints)
    
constraints = add.constraints(rep(1, n), 1, type = '=', constraints)  

weight <- min.risk.portfolio(ia, constraints)
weight
ifelse(!require(corpcor), install.packages("corpcor"), library(corpcor))
ifelse(!require(lpSolve), install.packages("lpSolve"), library(lpSolve))
ef = portopt(ia, constraints, 50, 'Efficient Frontier') 
ef

```


## Q3. Repeat Q1 and Q2 using weekly and monthly returns.
```{r}
library(tibbletime)
library(timetk)
library(fBasics)
library(quadprog)
 
weekly <- prices %>% 
  tk_tbl(rename_index= "date") %>%
    as_tbl_time(index= date) %>%
    as_period(period= "week", side= "end")
Sigma1 = cov(weekly[,2:4])
std1 = sqrt(diag(Sigma1))
mu = apply(weekly[,2:4], 2, mean)

Amat2 = cbind(rep(1,3),mu, diag(1,nrow=3))  
t(Amat2)
muP2 = seq(min(mu)+.0001, max(mu)-.0001,  length = 150)
sdP2 = muP2
weights2 = matrix(0,nrow=150,ncol=3) 

i=1
for (i in 1:length(muP2))  
    
{
  bvec2 = c(1,muP2[i], rep(0,3)) 
  result = solve.QP(Dmat=2*Sigma1,dvec=rep(0,3),Amat=Amat2,bvec=bvec2,meq=2)
  sdP2[i] = sqrt(result$value)
  weights2[i,] = result$solution
}

plot(sdP2,muP2,type="l",xlim=c(0,0.25),ylim=c(0,0.08),lty=1)
mufree.w = 0.01/12 
points(0,mufree.w,cex=3, pch="*")  
sharpe =( muP2-mufree.w)/sdP2
ind1 = (sharpe == max(sharpe)) 
options(digits=3)
weights2[ind1,] 
lines(c(0,2),mufree.w+c(0,2)*(muP2[ind1]-mufree.w)/sdP2[ind1],lwd=2,lty=3)

points(sdP2[ind1],muP2[ind1],cex=1,pch=19, col="red") 
ind2 = (sdP2 == min(sdP2)) 
points(sdP2[ind2],muP2[ind2],cex=2,pch="+", col="blue") 
ind3 = (muP2 > muP2[ind2])
lines(sdP2[ind3],muP2[ind3],type="l",xlim=c(0,.25),
      ylim=c(0,.08),lwd=1)  
points(c(std1[1],std1[2], std1[3]), c(mu[1], mu[2], mu[3]), cex=1, pch="o", col="red") 
text(std1[1],mu[1],"Costco",cex=1, pos=4)
text(std1[2],mu[2],"Wallmart",cex=1, pos=4)
text(std1[3],mu[3],"Target",cex=1, pos=4)
graphics.off()

```


```{r}
monthly <- prices %>% 
  tk_tbl(rename_index= "date") %>%
    as_tbl_time(index= date) %>%
    as_period(period= "month", side= "end")

Sigma2 = cov(monthly[,2:4])
std2= sqrt(diag(Sigma2))
mu = apply(monthly[,2:4], 2, mean)
Amat3 = cbind(rep(1,3),mu, diag(1,nrow=3))
t(Amat3)
muP3 = seq(min(mu)+.0001,max(mu)-.0001,length=300)
sdP3= muP3
weights3= matrix(0,nrow=300,ncol=3) 

i=1
for (i in 1:length(muP3))  
    
{
  bvec3 = c(1,muP3[i], rep(0,3)) 
  result = solve.QP(Dmat=2*Sigma2,dvec=rep(0,3),Amat=Amat3,bvec=bvec3,meq=2)
  sdP3[i] = sqrt(result$value)
  weights3[i,] = result$solution
}

plot(sdP3,muP3,type="l",xlim=c(0,0.25),ylim=c(0,0.08),lty=1)
mufree.m = 0.01/12 
points(0,mufree.m,cex=3, pch="*")  
sharpe =( muP3-mufree.m)/sdP3
ind2 = (sharpe == max(sharpe)) 
options(digits=3)
weights3[ind2,] 
lines(c(0,2),mufree.m+c(0,2)*(muP3[ind2]-mufree.m)/sdP3[ind2],lwd=2,lty=3)
points(sdP3[ind2],muP3[ind2],cex=1,pch=19, col="red") 
ind2 = (sdP3 == min(sdP3)) 
points(sdP3[ind2],muP3[ind2],cex=2,pch="+", col="blue") 

ind3 = (muP3 > muP3[ind2])
lines(sdP3[ind3],muP3[ind3],type="l",xlim=c(0,.25),
      ylim=c(0,.08),lwd=1) 
points(c(std[1],std[2], std[3]), c(mu[1], mu[2], mu[3]), cex=1, pch="o", col="red") 
text(std[1],mu[1],"Costco",cex=1, pos=4)
text(std[2],mu[2],"Wallmart",cex=1, pos=4)
text(std[3],mu[3],"Target",cex=1, pos=4)
graphics.off()

```





